# Score cache options
score_caches:
  ores_redis:
    class: ores.score_caches.Redis
    host: 127.0.0.1  # Local
    port: 6379  # Default port

scoring_systems:
  defaults:
    metrics_collector: local_logging  # Don't try to connect graphite
  celery_queue:
    broker_url: redis://127.0.0.1:6379  # Local
    result_backend: redis://127.0.0.1:6379  # Local
