logging:
  version: 1
  loggers:
    revscoring:
      level: ERROR
      handlers:
        - file
    ores:
      level: WARNING
      handlers:
        - file
    celery:
      level: WARNING
      handlers:
        - file
  handlers:
    stdout:
      class: logging.StreamHandler
      formatter: basic_human
      stream: ext://sys.stdout
    file:
      class: logging.handlers.TimedRotatingFileHandler
      filename: /srv/log/ores/app.log
      when: midnight
      backupCount: 7
    logstash:
      class: ores.logging.LogstashHandler
      host: deployment-logstash2.eqiad.wmflabs
      port: 12201
  formatters:
    basic_human:
      format: "%(asctime)s %(levelname)s:%(name)s -- %(message)s"

