# Scorers
scoring_contexts:
  arwiki:
    extractor: arwiki_api
    scorer_models:
      damaging: arwiki_damaging
      goodfaith: arwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  bnwiki:
    extractor: bnwiki_api
    scorer_models:
      reverted: bnwiki_revert
    precache:
      reverted:
        "on": ["edit"]
  bswiki:
    extractor: bswiki_api
    scorer_models:
      damaging: bswiki_damaging
      goodfaith: bswiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  cawiki:
    extractor: cawiki_api
    scorer_models:
      damaging: cawiki_damaging
      goodfaith: cawiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  cswiki:
    extractor: cswiki_api
    scorer_models:
      damaging: cswiki_damaging
      goodfaith: cswiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  dewiki:
    extractor: dewiki_api
    scorer_models:
      damaging: dewiki_damaging
      goodfaith: dewiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  elwiki:
    extractor: elwiki_api
    scorer_models:
      reverted: elwiki_revert
    precache:
      reverted:
        "on": ["edit"]
  enwiki:
    extractor: enwiki_api
    scorer_models:
      wp10: enwiki_articlequality
      articlequality: enwiki_articlequality
      draftquality: enwiki_draftquality
      drafttopic: enwiki_drafttopic
      damaging: enwiki_damaging
      goodfaith: enwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      drafttopic:
        "on": ["page_creation"]
      goodfaith:
        "on": ["edit"]
  enwiktionary:
    extractor: enwiktionary_api
    scorer_models:
      reverted: enwiktionary_revert
    precache:
      reverted:
        "on": ["edit"]
  eswikibooks:
    extractor: eswikibooks_api
    scorer_models:
      damaging: eswikibooks_damaging
      goodfaith: eswikibooks_goodfaith
    precache:
      reverted:
        "on": ["edit"]
  eswiki:
    extractor: eswiki_api
    scorer_models:
      damaging: eswiki_damaging
      goodfaith: eswiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  eswikiquote:
    extractor: eswikiquote_api
    scorer_models:
      damaging: eswikiquote_damaging
      goodfaith: eswikiquote_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  etwiki:
    extractor: etwiki_api
    scorer_models:
      damaging: etwiki_damaging
      goodfaith: etwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  euwiki:
    extractor: euwiki_api
    scorer_models:
      wp10: euwiki_articlequality
      articlequality: euwiki_articlequality
    precache:
      articlequality:
        "on": ["edit"]
  fawiki:
    extractor: fawiki_api
    scorer_models:
      damaging: fawiki_damaging
      goodfaith: fawiki_goodfaith
      wp10: fawiki_articlequality
      articlequality: fawiki_articlequality
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  fakewiki:
    extractor: fakewiki_offline
    scorer_models:
      damaging: fakewiki_model
      goodfaith: fakewiki_model
  fiwiki:
    extractor: fiwiki_api
    scorer_models:
      damaging: fiwiki_damaging
      goodfaith: fiwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  frwiki:
    extractor: frwiki_api
    scorer_models:
      damaging: frwiki_damaging
      goodfaith: frwiki_goodfaith
      wp10: frwiki_articlequality
      articlequality: frwiki_articlequality
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  frwikisource:
    extractor: frwikisource_api
    scorer_models:
      pagelevel: frwikisource_pagelevel
    precache:
      pagelevel:
        "on": ["edit"]
  glwiki:
    extractor: glwiki_api
    scorer_models:
      articlequality: glwiki_articlequality
      reverted: glwiki_revert
    precache:
      articlequality:
        "on": ["edit"]
      reverted:
        "on": ["edit"]
  hewiki:
    extractor: hewiki_api
    scorer_models:
      damaging: hewiki_damaging
      goodfaith: hewiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  hrwiki:
    extractor: hrwiki_api
    scorer_models:
      reverted: hrwiki_revert
    precache:
      reverted:
        "on": ["edit"]
  huwiki:
    extractor: huwiki_api
    scorer_models:
      damaging: huwiki_damaging
      goodfaith: huwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  idwiki:
    extractor: idwiki_api
    scorer_models:
      reverted: idwiki_revert
    precache:
      reverted:
        "on": ["edit"]
  iswiki:
    extractor: iswiki_api
    scorer_models:
      reverted: iswiki_revert
    precache:
      reverted:
        "on": ["edit"]
  itwiki:
    extractor: itwiki_api
    scorer_models:
      damaging: itwiki_damaging
      goodfaith: itwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  jawiki:
    extractor: jawiki_api
    scorer_models:
      damaging: jawiki_damaging
      goodfaith: jawiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  kowiki:
    extractor: kowiki_api
    scorer_models:
      damaging: kowiki_damaging
      goodfaith: kowiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  lvwiki:
    extractor: lvwiki_api
    scorer_models:
      damaging: lvwiki_damaging
      goodfaith: lvwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  nlwiki:
    extractor: nlwiki_api
    scorer_models:
      damaging: nlwiki_damaging
      goodfaith: nlwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  nowiki:
    extractor: nowiki_api
    scorer_models:
      reverted: nowiki_revert
    precache:
      reverted:
        "on": ["edit"]
  plwiki:
    extractor: plwiki_api
    scorer_models:
      goodfaith: plwiki_goodfaith
      damaging: plwiki_damaging
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  ptwiki:
    extractor: ptwiki_api
    scorer_models:
      damaging: ptwiki_damaging
      goodfaith: ptwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  rowiki:
    extractor: rowiki_api
    scorer_models:
      damaging: rowiki_damaging
      goodfaith: rowiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  ruwiki:
    extractor: ruwiki_api
    scorer_models:
      damaging: ruwiki_damaging
      goodfaith: ruwiki_goodfaith
      wp10: ruwiki_articlequality
      articlequality: ruwiki_articlequality
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  simplewiki:
    extractor: simplewiki_api
    scorer_models:
      wp10: enwiki_articlequality
      articlequality: enwiki_articlequality
      draftquality: enwiki_draftquality
      damaging: enwiki_damaging
      goodfaith: enwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  sqwiki:
    extractor: sqwiki_api
    scorer_models:
      damaging: sqwiki_damaging
      goodfaith: sqwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  srwiki:
    extractor: srwiki_api
    scorer_models:
      damaging: srwiki_damaging
      goodfaith: srwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  svwiki:
    extractor: svwiki_api
    scorer_models:
      damaging: svwiki_damaging
      goodfaith: svwiki_goodfaith
      articlequality: svwiki_articlequality
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
      articlequality:
        "on": ["edit"]
  tawiki:
    extractor: tawiki_api
    scorer_models:
      reverted: tawiki_revert
    precache:
      reverted:
        "on": ["edit"]
  testwiki:
    extractor: testwiki_api
    scorer_models:
      reverted: testwiki_revert
      damaging: testwiki_revert
      goodfaith: testwiki_revert
      wp10: enwiki_articlequality
      articlequality: enwiki_articlequality
      draftquality: enwiki_draftquality
    precache: {}
  translatewiki:
    extractor: translatewiki_api
    scorer_models:
      reverted: translatewiki_revert
    precache:
      reverted:
        "on": ["edit"]
  trwiki:
    extractor: trwiki_api
    scorer_models:
      damaging: trwiki_damaging
      goodfaith: trwiki_goodfaith
      wp10: trwiki_articlequality
      articlequality: trwiki_articlequality
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  ukwiki:
    extractor: ukwiki_api
    scorer_models:
      reverted: ukwiki_revert
    precache:
      reverted:
        "on": ["edit"]
  viwiki:
    extractor: viwiki_api
    scorer_models:
      reverted: viwiki_revert
    precache:
      reverted:
        "on": ["edit"]
  wikidatawiki:
    extractor: wikidata_api
    scorer_models:
      damaging: wikidata_damaging
      goodfaith: wikidata_goodfaith
      itemquality: wikidata_itemquality
    precache:
      damaging:
        "on": ["nonbot_edit"]
      goodfaith:
        "on": ["nonbot_edit"]
      itemquality:
        "on": ["edit"]
  zhwiki:
    extractor: zhwiki_api
    scorer_models:
      damaging: zhwiki_damaging
      goodfaith: zhwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
