# Scorer models
scorer_models:
  defaults:
    class: revscoring.Model
  arwiki_damaging:
    model_file: submodules/editquality/models/arwiki.damaging.gradient_boosting.model
  arwiki_goodfaith:
    model_file: submodules/editquality/models/arwiki.goodfaith.gradient_boosting.model
  bnwiki_revert:
    model_file: submodules/editquality/models/bnwiki.reverted.gradient_boosting.model
  bswiki_damaging:
    model_file: submodules/editquality/models/bswiki.damaging.rf.model
  bswiki_goodfaith:
    model_file: submodules/editquality/models/bswiki.goodfaith.gradient_boosting.model
  cawiki_damaging:
    model_file: submodules/editquality/models/cawiki.damaging.gradient_boosting.model
  cawiki_goodfaith:
    model_file: submodules/editquality/models/cawiki.goodfaith.gradient_boosting.model
  cswiki_damaging:
    model_file: submodules/editquality/models/cswiki.damaging.gradient_boosting.model
  cswiki_goodfaith:
    model_file: submodules/editquality/models/cswiki.goodfaith.gradient_boosting.model
  dewiki_damaging:
    model_file: submodules/editquality/models/dewiki.damaging.gradient_boosting.model
  dewiki_goodfaith:
    model_file: submodules/editquality/models/dewiki.goodfaith.gradient_boosting.model
  elwiki_revert:
    model_file: submodules/editquality/models/elwiki.reverted.gradient_boosting.model
  enwiki_draftquality:
    model_file: submodules/draftquality/models/enwiki.draft_quality.gradient_boosting.model.bz2
  enwiki_drafttopic:
    model_file: submodules/drafttopic/models/enwiki.drafttopic.gradient_boosting.model
  enwiki_articlequality:
    model_file: submodules/articlequality/models/enwiki.nettrom_wp10.gradient_boosting.model
  enwiki_damaging:
    model_file: submodules/editquality/models/enwiki.damaging.gradient_boosting.model
  enwiki_goodfaith:
    model_file: submodules/editquality/models/enwiki.goodfaith.gradient_boosting.model
  enwiktionary_revert:
    model_file: submodules/editquality/models/enwiktionary.reverted.rf.model
  eswiki_damaging:
    model_file: submodules/editquality/models/eswiki.damaging.gradient_boosting.model
  eswiki_goodfaith:
    model_file: submodules/editquality/models/eswiki.goodfaith.gradient_boosting.model
  eswikibooks_damaging:
    model_file: submodules/editquality/models/eswikibooks.damaging.gradient_boosting.model
  eswikibooks_goodfaith:
    model_file: submodules/editquality/models/eswikibooks.goodfaith.gradient_boosting.model
  eswikiquote_damaging:
    model_file: submodules/editquality/models/eswikiquote.damaging.gradient_boosting.model
  eswikiquote_goodfaith:
    model_file: submodules/editquality/models/eswikiquote.goodfaith.gradient_boosting.model
  etwiki_damaging:
    model_file: submodules/editquality/models/etwiki.damaging.gradient_boosting.model
  etwiki_goodfaith:
    model_file: submodules/editquality/models/etwiki.goodfaith.gradient_boosting.model
  euwiki_articlequality:
    model_file: submodules/articlequality/models/euwiki.wp10.gradient_boosting.model
  fawiki_damaging:
    model_file: submodules/editquality/models/fawiki.damaging.gradient_boosting.model
  fawiki_goodfaith:
    model_file: submodules/editquality/models/fawiki.goodfaith.gradient_boosting.model
  fawiki_articlequality:
    model_file: submodules/articlequality/models/fawiki.wp10.gradient_boosting.model
  fakewiki_model:
    class: ores.scoring.models.RevIdScorer
    version: 0.0.3
  fiwiki_damaging:
    model_file: submodules/editquality/models/fiwiki.damaging.gradient_boosting.model
  fiwiki_goodfaith:
    model_file: submodules/editquality/models/fiwiki.goodfaith.gradient_boosting.model
  frwiki_damaging:
    model_file: submodules/editquality/models/frwiki.damaging.gradient_boosting.model
  frwiki_goodfaith:
    model_file: submodules/editquality/models/frwiki.goodfaith.gradient_boosting.model
  frwiki_articlequality:
    model_file: submodules/articlequality/models/frwiki.wp10.gradient_boosting.model
  frwikisource_pagelevel:
    model_file: submodules/articlequality/models/frwikisource.page_level.gradient_boosting.model
  glwiki_articlequality:
    model_file: submodules/articlequality/models/glwiki.wp10.gradient_boosting.model
  glwiki_revert:
    model_file: submodules/editquality/models/glwiki.reverted.gradient_boosting.model
  hewiki_damaging:
    model_file: submodules/editquality/models/hewiki.damaging.rf.model
  hewiki_goodfaith:
    model_file: submodules/editquality/models/hewiki.goodfaith.gradient_boosting.model
  hrwiki_revert:
    model_file: submodules/editquality/models/hrwiki.reverted.gradient_boosting.model
  huwiki_damaging:
    model_file: submodules/editquality/models/huwiki.damaging.gradient_boosting.model
  huwiki_goodfaith:
    model_file: submodules/editquality/models/huwiki.goodfaith.gradient_boosting.model
  idwiki_revert:
    model_file: submodules/editquality/models/idwiki.reverted.gradient_boosting.model
  iswiki_revert:
    model_file: submodules/editquality/models/iswiki.reverted.gradient_boosting.model
  itwiki_damaging:
    model_file: submodules/editquality/models/itwiki.damaging.gradient_boosting.model
  itwiki_goodfaith:
    model_file: submodules/editquality/models/itwiki.goodfaith.gradient_boosting.model
  jawiki_damaging:
    model_file: submodules/editquality/models/jawiki.damaging.gradient_boosting.model
  jawiki_goodfaith:
    model_file: submodules/editquality/models/jawiki.goodfaith.gradient_boosting.model
  kowiki_damaging:
    model_file: submodules/editquality/models/kowiki.damaging.gradient_boosting.model
  kowiki_goodfaith:
    model_file: submodules/editquality/models/kowiki.goodfaith.gradient_boosting.model
  lvwiki_damaging:
    model_file: submodules/editquality/models/lvwiki.damaging.gradient_boosting.model
  lvwiki_goodfaith:
    model_file: submodules/editquality/models/lvwiki.goodfaith.gradient_boosting.model
  nlwiki_damaging:
    model_file: submodules/editquality/models/nlwiki.damaging.gradient_boosting.model
  nlwiki_goodfaith:
    model_file: submodules/editquality/models/nlwiki.goodfaith.gradient_boosting.model
  nowiki_revert:
    model_file: submodules/editquality/models/nowiki.reverted.gradient_boosting.model
  plwiki_damaging:
    model_file: submodules/editquality/models/plwiki.damaging.gradient_boosting.model
  plwiki_goodfaith:
    model_file: submodules/editquality/models/plwiki.goodfaith.rf.model
  ptwiki_damaging:
    model_file: submodules/editquality/models/ptwiki.damaging.gradient_boosting.model
  ptwiki_goodfaith:
    model_file: submodules/editquality/models/ptwiki.goodfaith.gradient_boosting.model
  rowiki_revert:
    model_file: submodules/editquality/models/rowiki.reverted.gradient_boosting.model
  rowiki_damaging:
    model_file: submodules/editquality/models/rowiki.damaging.gradient_boosting.model
  rowiki_goodfaith:
    model_file: submodules/editquality/models/rowiki.goodfaith.gradient_boosting.model
  ruwiki_damaging:
    model_file: submodules/editquality/models/ruwiki.damaging.gradient_boosting.model
  ruwiki_goodfaith:
    model_file: submodules/editquality/models/ruwiki.goodfaith.gradient_boosting.model
  ruwiki_articlequality:
    model_file: submodules/articlequality/models/ruwiki.wp10.gradient_boosting.model
  sqwiki_damaging:
    model_file: submodules/editquality/models/sqwiki.damaging.gradient_boosting.model
  sqwiki_goodfaith:
    model_file: submodules/editquality/models/sqwiki.goodfaith.gradient_boosting.model
  srwiki_damaging:
    model_file: submodules/editquality/models/srwiki.damaging.gradient_boosting.model
  srwiki_goodfaith:
    model_file: submodules/editquality/models/srwiki.goodfaith.gradient_boosting.model
  svwiki_articlequality:
    model_file: submodules/articlequality/models/svwiki.wp10.gradient_boosting.model
  svwiki_damaging:
    model_file: submodules/editquality/models/svwiki.damaging.gradient_boosting.model
  svwiki_goodfaith:
    model_file: submodules/editquality/models/svwiki.goodfaith.gradient_boosting.model
  testwiki_revert:
    class: ores.scoring.models.RevIdScorer
    version: 0.0.3
  tawiki_revert:
    model_file: submodules/editquality/models/tawiki.reverted.gradient_boosting.model
  translatewiki_revert:
    model_file: submodules/editquality/models/translatewiki.reverted.gradient_boosting.model
  trwiki_damaging:
    model_file: submodules/editquality/models/trwiki.damaging.gradient_boosting.model
  trwiki_goodfaith:
    model_file: submodules/editquality/models/trwiki.goodfaith.gradient_boosting.model
  trwiki_articlequality:
    model_file: submodules/articlequality/models/trwiki.wp10.gradient_boosting.model
  ukwiki_revert:
    model_file: submodules/editquality/models/ukwiki.reverted.gradient_boosting.model
  viwiki_revert:
    model_file: submodules/editquality/models/viwiki.reverted.gradient_boosting.model
  wikidata_damaging:
    model_file: submodules/editquality/models/wikidatawiki.damaging.gradient_boosting.model
  wikidata_goodfaith:
    model_file: submodules/editquality/models/wikidatawiki.goodfaith.gradient_boosting.model
  wikidata_itemquality:
    model_file: submodules/articlequality/models/wikidatawiki.item_quality.gradient_boosting.model
  zhwiki_damaging:
    model_file: submodules/editquality/models/zhwiki.damaging.gradient_boosting.model
  zhwiki_goodfaith:
    model_file: submodules/editquality/models/zhwiki.goodfaith.gradient_boosting.model
