scoring_systems:
  defaults:
    scoring_contexts:
      - arwiki
      - bnwiki
      - bswiki
      - cawiki
      - cswiki
      - dewiki
      - elwiki
      - enwiki
      - enwiktionary
      - eswikibooks
      - eswiki
      - eswikiquote
      - etwiki
      - euwiki
      - fawiki
      - fakewiki
      - fiwiki
      - frwiki
      - frwikisource
      - glwiki
      - hewiki
      - hrwiki
      - huwiki
      - idwiki
      - iswiki
      - itwiki
      - jawiki
      - kowiki
      - lvwiki
      - nlwiki
      - nowiki
      - plwiki
      - ptwiki
      - rowiki
      - ruwiki
      - simplewiki
      - sqwiki
      - srwiki
      - svwiki
      - testwiki
      - tawiki
      - translatewiki
      - trwiki
      - ukwiki
      - viwiki
      - wikidatawiki
      - zhwiki
